file:
  '*.ts': 'kabab-case'
  '*.tsx': 'kabab-case'
  '*.js': 'kabab-case'
  '*.jsx': 'kabab-case'
  '*.json': 'kabab-case'
  '*.md': 'kabab-case'
  '*.yml': 'kabab-case'
  '*.yaml': 'kabab-case'
  '*.scss': 'kabab-case'
  '*.css': 'kabab-case'
  '*.py': 'snake_case'
  '*.rs': 'snake_case'
  '*.swift': 'PascalCase'
ignore:
  - 'node_modules/**'
  - 'dist/**'
  - 'build/**'
  - 'coverage/**'
  - '.venv/**'
  - '**/generated/**'
  - '**/__generated__/**'
  - '**/schema/**'
  - '**/schemas/**'
  - '**/*.config.*'
  - '**/metro.config.*'
  - '**/babel.config.*'
  - '**/jest.config.*'
  - '**/webpack.config.*'
  - '**/rollup.config.*'
  - 'mobile/src-tauri/gen/**/*'
