packages:
  - mobile
  - ts-schema
  - presentation
catalog:
  "@emnapi/core": ^1.5.0
  "@emnapi/runtime": ^1.5.0
  "@iconify-icons/mdi": ^1.2.48
  "@iconify/icons-mdi": ^1.2.48
  "@iconify/json": ^2.2.377
  "@iconify/vue": ^5.0.0
  "@ls-lint/ls-lint": ^2.3.1
  "@mnlphlp/plugin-blec": ^0.8.0
  "@napi-rs/cli": ^3.2.0
  "@oxc-node/core": ^0.0.32
  "@tailwindcss/vite": ^4.1.12
  "@taplo/cli": ^0.7.0
  "@tauri-apps/api": ^2.8.0
  "@tauri-apps/cli": ^2.8.1
  "@tauri-apps/plugin-biometric": ~2
  "@tauri-apps/plugin-fs": ~2
  "@tauri-apps/plugin-geolocation": ~2
  "@tauri-apps/plugin-http": ~2
  "@tauri-apps/plugin-log": ^2.7.0
  "@tauri-apps/plugin-nfc": ~2
  "@tauri-apps/plugin-notification": ~2
  "@tauri-apps/plugin-opener": ^2.5.0
  "@tauri-apps/plugin-sql": ~2
  "@tybys/wasm-util": ^0.10.0
  "@types/node": ^24.3.0
  "@vee-validate/zod": ^4.15.1
  "@vitejs/plugin-vue": ^6.0.1
  "@vitejs/plugin-vue-jsx": ^5.0.1
  "@vue/test-utils": ^2.4.6
  "@vueuse/core": ^13.7.0
  "@vueuse/math": ^13.7.0
  ava: ^6.4.1
  chalk: ^5.6.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dayjs: ^1.11.13
  geojson: ^0.5.0
  husky: ^9.1.7
  konva: ^9.3.22
  lint-staged: ^16.1.6
  lucide-vue-next: ^0.540.0
  maplibre-gl: ^5.6.2
  motion-v: ^1.7.0
  npm-run-all2: ^8.0.4
  pinia: ^3.0.3
  pinia-plugin-persistedstate: ^4.5.0
  prettier: ^3.6.2
  reka-ui: ^2.4.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.12
  tinybench: ^5.0.1
  tw-animate-css: ^1.3.7
  vconsole: ^3.15.1
  vee-validate: ^4.15.1
  vite: npm:rolldown-vite@latest
  vite-plugin-vue-devtools: ^8.0.2
  vitest: ^3.2.4
  vue: ^3.5.18
  vue-i18n: ^11.1.11
  vue-konva: ^3.2.2
  vue-maplibre-gl: ^5.5.9
  vue-router: ^4.5.1
  vue-tsc: ^3.0.5
  zod: ^4.1.1
  typescript: ^5.9.2
  oxlint: ^1.24.0
  oxlint-tsgolint: ^0.4.0
