init:
  pnpm install
  cd src-tauri && cargo build

fmt:
  pnpm run format
  cd src-tauri && cargo fmt

lint:
  pnpm run lint
  echo "Oxlint Tsgolint hasn't production-ready yet, and we couldn't disable certain rules for now."
  cd src-tauri && cargo clippy --all-targets --all-features -- -D warnings

fix:
  pnpm run fix
  cd src-tauri && cargo clippy --all-targets --all-features --fix -- -D warnings

test:
  pnpm run test
  cd src-tauri && cargo test

fmt-check:
  pnpm run format:check
  cd src-tauri && cargo fmt -- --check

clean:
  pnpm run clean
  cd src-tauri && cargo clean

check:
  pnpm run check
  cd src-tauri && cargo check