# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import plot_pb2 as plot__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlotServiceStub(object):
    """PlotService for floor plan polygon extraction
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractPolygons = channel.unary_unary(
                '/plot.PlotService/ExtractPolygons',
                request_serializer=plot__pb2.ExtractPolygonsRequest.SerializeToString,
                response_deserializer=plot__pb2.ExtractPolygonsResponse.FromString,
                _registered_method=True)
        self.BatchExtract = channel.unary_unary(
                '/plot.PlotService/BatchExtract',
                request_serializer=plot__pb2.BatchExtractRequest.SerializeToString,
                response_deserializer=plot__pb2.BatchExtractResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/plot.PlotService/HealthCheck',
                request_serializer=plot__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=plot__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PlotServiceServicer(object):
    """PlotService for floor plan polygon extraction
    """

    def ExtractPolygons(self, request, context):
        """Extract polygons from a single floor plan
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchExtract(self, request, context):
        """Batch extract polygons from multiple floor plans
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractPolygons': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractPolygons,
                    request_deserializer=plot__pb2.ExtractPolygonsRequest.FromString,
                    response_serializer=plot__pb2.ExtractPolygonsResponse.SerializeToString,
            ),
            'BatchExtract': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchExtract,
                    request_deserializer=plot__pb2.BatchExtractRequest.FromString,
                    response_serializer=plot__pb2.BatchExtractResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=plot__pb2.HealthCheckRequest.FromString,
                    response_serializer=plot__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plot.PlotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('plot.PlotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlotService(object):
    """PlotService for floor plan polygon extraction
    """

    @staticmethod
    def ExtractPolygons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plot.PlotService/ExtractPolygons',
            plot__pb2.ExtractPolygonsRequest.SerializeToString,
            plot__pb2.ExtractPolygonsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchExtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plot.PlotService/BatchExtract',
            plot__pb2.BatchExtractRequest.SerializeToString,
            plot__pb2.BatchExtractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plot.PlotService/HealthCheck',
            plot__pb2.HealthCheckRequest.SerializeToString,
            plot__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
