# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import task_pb2 as task__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in task_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class OrchestratorServiceStub(object):
    """============================================================================
    Services
    ============================================================================

    OrchestratorService is implemented by Rust orchestrator (server)
    Go tower acts as client to report robot status and receive task assignments
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportRobotStatus = channel.unary_unary(
            "/task.OrchestratorService/ReportRobotStatus",
            request_serializer=task__pb2.RobotReportRequest.SerializeToString,
            response_deserializer=task__pb2.RobotReportResponse.FromString,
            _registered_method=True,
        )
        self.GetTaskAssignment = channel.unary_stream(
            "/task.OrchestratorService/GetTaskAssignment",
            request_serializer=task__pb2.RobotDistributionRequest.SerializeToString,
            response_deserializer=task__pb2.TaskAssignment.FromString,
            _registered_method=True,
        )
        self.ExtractPolygons = channel.unary_unary(
            "/task.OrchestratorService/ExtractPolygons",
            request_serializer=task__pb2.ExtractPolygonsRequest.SerializeToString,
            response_deserializer=task__pb2.ExtractPolygonsResponse.FromString,
            _registered_method=True,
        )
        self.BatchExtractPolygons = channel.unary_unary(
            "/task.OrchestratorService/BatchExtractPolygons",
            request_serializer=task__pb2.BatchExtractRequest.SerializeToString,
            response_deserializer=task__pb2.BatchExtractResponse.FromString,
            _registered_method=True,
        )


class OrchestratorServiceServicer(object):
    """============================================================================
    Services
    ============================================================================

    OrchestratorService is implemented by Rust orchestrator (server)
    Go tower acts as client to report robot status and receive task assignments
    """

    def ReportRobotStatus(self, request, context):
        """ReportRobotStatus is called by Go tower to report robot status"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTaskAssignment(self, request, context):
        """GetTaskAssignment is called by Go tower to get tasks for robots
        This could be streaming or polling based on implementation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExtractPolygons(self, request, context):
        """Plot extraction methods (called by Python plot client)

        ExtractPolygons extracts polygons from a single floor plan
        Python plot client calls this with the floor plan image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchExtractPolygons(self, request, context):
        """BatchExtractPolygons extracts polygons from multiple floor plans"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_OrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ReportRobotStatus": grpc.unary_unary_rpc_method_handler(
            servicer.ReportRobotStatus,
            request_deserializer=task__pb2.RobotReportRequest.FromString,
            response_serializer=task__pb2.RobotReportResponse.SerializeToString,
        ),
        "GetTaskAssignment": grpc.unary_stream_rpc_method_handler(
            servicer.GetTaskAssignment,
            request_deserializer=task__pb2.RobotDistributionRequest.FromString,
            response_serializer=task__pb2.TaskAssignment.SerializeToString,
        ),
        "ExtractPolygons": grpc.unary_unary_rpc_method_handler(
            servicer.ExtractPolygons,
            request_deserializer=task__pb2.ExtractPolygonsRequest.FromString,
            response_serializer=task__pb2.ExtractPolygonsResponse.SerializeToString,
        ),
        "BatchExtractPolygons": grpc.unary_unary_rpc_method_handler(
            servicer.BatchExtractPolygons,
            request_deserializer=task__pb2.BatchExtractRequest.FromString,
            response_serializer=task__pb2.BatchExtractResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "task.OrchestratorService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "task.OrchestratorService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class OrchestratorService(object):
    """============================================================================
    Services
    ============================================================================

    OrchestratorService is implemented by Rust orchestrator (server)
    Go tower acts as client to report robot status and receive task assignments
    """

    @staticmethod
    def ReportRobotStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/task.OrchestratorService/ReportRobotStatus",
            task__pb2.RobotReportRequest.SerializeToString,
            task__pb2.RobotReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTaskAssignment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/task.OrchestratorService/GetTaskAssignment",
            task__pb2.RobotDistributionRequest.SerializeToString,
            task__pb2.TaskAssignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExtractPolygons(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/task.OrchestratorService/ExtractPolygons",
            task__pb2.ExtractPolygonsRequest.SerializeToString,
            task__pb2.ExtractPolygonsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BatchExtractPolygons(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/task.OrchestratorService/BatchExtractPolygons",
            task__pb2.BatchExtractRequest.SerializeToString,
            task__pb2.BatchExtractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
