// Auto-generated TypeScript declarations from Rust schema
// All types are generated by ts-rs from shared/src/schema/

// Re-export all schema types from generated folder
export * from './generated/Area'
export * from './generated/Beacon'
export * from './generated/BeaconDevice'
export * from './generated/BeaconType'
export * from './generated/ChineseFoodCuisine'
export * from './generated/Connection'
export * from './generated/ConnectionType'
export * from './generated/Entity'
export * from './generated/EntityType'
export * from './generated/FacilityType'
export * from './generated/Floor'
export * from './generated/FloorType'
export * from './generated/FoodCuisine'
export * from './generated/FoodType'
export * from './generated/Merchant'
export * from './generated/MerchantStyle'
export * from './generated/MerchantType'
export * from './generated/SocialMedia'
export * from './generated/SocialMediaPlatform'
