// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/task.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskType defines the type of task to be executed
type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_TASK_TYPE_DELIVERY    TaskType = 1
	TaskType_TASK_TYPE_PATROL      TaskType = 2
	TaskType_TASK_TYPE_RETURN_HOME TaskType = 3
	TaskType_TASK_TYPE_EMERGENCY   TaskType = 4
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_DELIVERY",
		2: "TASK_TYPE_PATROL",
		3: "TASK_TYPE_RETURN_HOME",
		4: "TASK_TYPE_EMERGENCY",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"TASK_TYPE_DELIVERY":    1,
		"TASK_TYPE_PATROL":      2,
		"TASK_TYPE_RETURN_HOME": 3,
		"TASK_TYPE_EMERGENCY":   4,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_task_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_proto_task_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{0}
}

// Priority level for task execution
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_NORMAL      Priority = 2
	Priority_PRIORITY_HIGH        Priority = 3
	Priority_PRIORITY_URGENT      Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_URGENT",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_NORMAL":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_URGENT":      4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_task_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_proto_task_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{1}
}

// RobotStatus represents the current state of a robot
type RobotState int32

const (
	RobotState_ROBOT_STATE_UNSPECIFIED RobotState = 0
	RobotState_ROBOT_STATE_IDLE        RobotState = 1
	RobotState_ROBOT_STATE_BUSY        RobotState = 2
	RobotState_ROBOT_STATE_CHARGING    RobotState = 3
	RobotState_ROBOT_STATE_ERROR       RobotState = 4
	RobotState_ROBOT_STATE_OFFLINE     RobotState = 5
)

// Enum value maps for RobotState.
var (
	RobotState_name = map[int32]string{
		0: "ROBOT_STATE_UNSPECIFIED",
		1: "ROBOT_STATE_IDLE",
		2: "ROBOT_STATE_BUSY",
		3: "ROBOT_STATE_CHARGING",
		4: "ROBOT_STATE_ERROR",
		5: "ROBOT_STATE_OFFLINE",
	}
	RobotState_value = map[string]int32{
		"ROBOT_STATE_UNSPECIFIED": 0,
		"ROBOT_STATE_IDLE":        1,
		"ROBOT_STATE_BUSY":        2,
		"ROBOT_STATE_CHARGING":    3,
		"ROBOT_STATE_ERROR":       4,
		"ROBOT_STATE_OFFLINE":     5,
	}
)

func (x RobotState) Enum() *RobotState {
	p := new(RobotState)
	*p = x
	return p
}

func (x RobotState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RobotState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_task_proto_enumTypes[2].Descriptor()
}

func (RobotState) Type() protoreflect.EnumType {
	return &file_proto_task_proto_enumTypes[2]
}

func (x RobotState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RobotState.Descriptor instead.
func (RobotState) EnumDescriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{2}
}

// Location represents a point with coordinates
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	Floor         string                 `protobuf:"bytes,4,opt,name=floor,proto3" json:"floor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Location) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Location) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Location) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

// Task represents a work item to be assigned to a robot
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          TaskType               `protobuf:"varint,2,opt,name=type,proto3,enum=task.TaskType" json:"type,omitempty"`
	Sources       []*Location            `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`     // Starting locations
	Terminals     []*Location            `protobuf:"bytes,4,rep,name=terminals,proto3" json:"terminals,omitempty"` // Destination locations
	Priority      Priority               `protobuf:"varint,5,opt,name=priority,proto3,enum=task.Priority" json:"priority,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                       // Unix timestamp
	EntityId      string                 `protobuf:"bytes,7,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`                                                           // Entity/mall identifier
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional task parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *Task) GetSources() []*Location {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *Task) GetTerminals() []*Location {
	if x != nil {
		return x.Terminals
	}
	return nil
}

func (x *Task) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Task) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Task) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// TaskRequest is sent from the Rust orchestrator to assign a task
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// TaskResponse acknowledges task receipt and assignment
type TaskResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Accepted                bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RobotId                 string                 `protobuf:"bytes,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"` // ID of robot assigned to task
	Message                 string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EstimatedCompletionTime int64                  `protobuf:"varint,4,opt,name=estimated_completion_time,json=estimatedCompletionTime,proto3" json:"estimated_completion_time,omitempty"` // Unix timestamp
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TaskResponse) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *TaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskResponse) GetEstimatedCompletionTime() int64 {
	if x != nil {
		return x.EstimatedCompletionTime
	}
	return 0
}

// RobotInfo contains robot identification and status
type RobotInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State           RobotState             `protobuf:"varint,3,opt,name=state,proto3,enum=task.RobotState" json:"state,omitempty"`
	CurrentLocation *Location              `protobuf:"bytes,4,opt,name=current_location,json=currentLocation,proto3" json:"current_location,omitempty"`
	BatteryLevel    float64                `protobuf:"fixed64,5,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"` // Percentage 0-100
	CurrentTaskId   string                 `protobuf:"bytes,6,opt,name=current_task_id,json=currentTaskId,proto3" json:"current_task_id,omitempty"`
	LastSeen        int64                  `protobuf:"varint,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"` // Unix timestamp
	EntityId        string                 `protobuf:"bytes,8,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RobotInfo) Reset() {
	*x = RobotInfo{}
	mi := &file_proto_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotInfo) ProtoMessage() {}

func (x *RobotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotInfo.ProtoReflect.Descriptor instead.
func (*RobotInfo) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{4}
}

func (x *RobotInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RobotInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RobotInfo) GetState() RobotState {
	if x != nil {
		return x.State
	}
	return RobotState_ROBOT_STATE_UNSPECIFIED
}

func (x *RobotInfo) GetCurrentLocation() *Location {
	if x != nil {
		return x.CurrentLocation
	}
	return nil
}

func (x *RobotInfo) GetBatteryLevel() float64 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *RobotInfo) GetCurrentTaskId() string {
	if x != nil {
		return x.CurrentTaskId
	}
	return ""
}

func (x *RobotInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *RobotInfo) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

// RobotDistributionRequest asks for current robot status
type RobotDistributionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotDistributionRequest) Reset() {
	*x = RobotDistributionRequest{}
	mi := &file_proto_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotDistributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotDistributionRequest) ProtoMessage() {}

func (x *RobotDistributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotDistributionRequest.ProtoReflect.Descriptor instead.
func (*RobotDistributionRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{5}
}

func (x *RobotDistributionRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

// RobotDistributionResponse returns information about all robots
type RobotDistributionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Robots        []*RobotInfo           `protobuf:"bytes,1,rep,name=robots,proto3" json:"robots,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	IdleCount     int32                  `protobuf:"varint,3,opt,name=idle_count,json=idleCount,proto3" json:"idle_count,omitempty"`
	BusyCount     int32                  `protobuf:"varint,4,opt,name=busy_count,json=busyCount,proto3" json:"busy_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotDistributionResponse) Reset() {
	*x = RobotDistributionResponse{}
	mi := &file_proto_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotDistributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotDistributionResponse) ProtoMessage() {}

func (x *RobotDistributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotDistributionResponse.ProtoReflect.Descriptor instead.
func (*RobotDistributionResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{6}
}

func (x *RobotDistributionResponse) GetRobots() []*RobotInfo {
	if x != nil {
		return x.Robots
	}
	return nil
}

func (x *RobotDistributionResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *RobotDistributionResponse) GetIdleCount() int32 {
	if x != nil {
		return x.IdleCount
	}
	return 0
}

func (x *RobotDistributionResponse) GetBusyCount() int32 {
	if x != nil {
		return x.BusyCount
	}
	return 0
}

// RobotReportRequest is sent from Go tower to Rust orchestrator
type RobotReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Robot         *RobotInfo             `protobuf:"bytes,1,opt,name=robot,proto3" json:"robot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotReportRequest) Reset() {
	*x = RobotReportRequest{}
	mi := &file_proto_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotReportRequest) ProtoMessage() {}

func (x *RobotReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotReportRequest.ProtoReflect.Descriptor instead.
func (*RobotReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{7}
}

func (x *RobotReportRequest) GetRobot() *RobotInfo {
	if x != nil {
		return x.Robot
	}
	return nil
}

// RobotReportResponse acknowledges the report
type RobotReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotReportResponse) Reset() {
	*x = RobotReportResponse{}
	mi := &file_proto_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotReportResponse) ProtoMessage() {}

func (x *RobotReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotReportResponse.ProtoReflect.Descriptor instead.
func (*RobotReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{8}
}

func (x *RobotReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RobotReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TaskAssignment is sent from Rust orchestrator to Go tower
type TaskAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_proto_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{9}
}

func (x *TaskAssignment) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *TaskAssignment) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// TaskAssignmentResponse acknowledges task assignment
type TaskAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignmentResponse) Reset() {
	*x = TaskAssignmentResponse{}
	mi := &file_proto_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignmentResponse) ProtoMessage() {}

func (x *TaskAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignmentResponse.ProtoReflect.Descriptor instead.
func (*TaskAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{10}
}

func (x *TaskAssignmentResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TaskAssignmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_task_proto protoreflect.FileDescriptor

const file_proto_task_proto_rawDesc = "" +
	"\n" +
	"\x10proto/task.proto\x12\x04task\"J\n" +
	"\bLocation\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\x12\x14\n" +
	"\x05floor\x18\x04 \x01(\tR\x05floor\"\xed\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0e.task.TaskTypeR\x04type\x12(\n" +
	"\asources\x18\x03 \x03(\v2\x0e.task.LocationR\asources\x12,\n" +
	"\tterminals\x18\x04 \x03(\v2\x0e.task.LocationR\tterminals\x12*\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x0e.task.PriorityR\bpriority\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\tentity_id\x18\a \x01(\tR\bentityId\x124\n" +
	"\bmetadata\x18\b \x03(\v2\x18.task.Task.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\vTaskRequest\x12\x1e\n" +
	"\x04task\x18\x01 \x01(\v2\n" +
	".task.TaskR\x04task\"\x9b\x01\n" +
	"\fTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x19\n" +
	"\brobot_id\x18\x02 \x01(\tR\arobotId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12:\n" +
	"\x19estimated_completion_time\x18\x04 \x01(\x03R\x17estimatedCompletionTime\"\x99\x02\n" +
	"\tRobotInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x05state\x18\x03 \x01(\x0e2\x10.task.RobotStateR\x05state\x129\n" +
	"\x10current_location\x18\x04 \x01(\v2\x0e.task.LocationR\x0fcurrentLocation\x12#\n" +
	"\rbattery_level\x18\x05 \x01(\x01R\fbatteryLevel\x12&\n" +
	"\x0fcurrent_task_id\x18\x06 \x01(\tR\rcurrentTaskId\x12\x1b\n" +
	"\tlast_seen\x18\a \x01(\x03R\blastSeen\x12\x1b\n" +
	"\tentity_id\x18\b \x01(\tR\bentityId\"7\n" +
	"\x18RobotDistributionRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"\xa3\x01\n" +
	"\x19RobotDistributionResponse\x12'\n" +
	"\x06robots\x18\x01 \x03(\v2\x0f.task.RobotInfoR\x06robots\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1d\n" +
	"\n" +
	"idle_count\x18\x03 \x01(\x05R\tidleCount\x12\x1d\n" +
	"\n" +
	"busy_count\x18\x04 \x01(\x05R\tbusyCount\";\n" +
	"\x12RobotReportRequest\x12%\n" +
	"\x05robot\x18\x01 \x01(\v2\x0f.task.RobotInfoR\x05robot\"I\n" +
	"\x13RobotReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x0eTaskAssignment\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12\x1e\n" +
	"\x04task\x18\x02 \x01(\v2\n" +
	".task.TaskR\x04task\"N\n" +
	"\x16TaskAssignmentResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x87\x01\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_TYPE_DELIVERY\x10\x01\x12\x14\n" +
	"\x10TASK_TYPE_PATROL\x10\x02\x12\x19\n" +
	"\x15TASK_TYPE_RETURN_HOME\x10\x03\x12\x17\n" +
	"\x13TASK_TYPE_EMERGENCY\x10\x04*s\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x13\n" +
	"\x0fPRIORITY_URGENT\x10\x04*\x9f\x01\n" +
	"\n" +
	"RobotState\x12\x1b\n" +
	"\x17ROBOT_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ROBOT_STATE_IDLE\x10\x01\x12\x14\n" +
	"\x10ROBOT_STATE_BUSY\x10\x02\x12\x18\n" +
	"\x14ROBOT_STATE_CHARGING\x10\x03\x12\x15\n" +
	"\x11ROBOT_STATE_ERROR\x10\x04\x12\x17\n" +
	"\x13ROBOT_STATE_OFFLINE\x10\x052\xac\x01\n" +
	"\x13OrchestratorService\x12H\n" +
	"\x11ReportRobotStatus\x12\x18.task.RobotReportRequest\x1a\x19.task.RobotReportResponse\x12K\n" +
	"\x11GetTaskAssignment\x12\x1e.task.RobotDistributionRequest\x1a\x14.task.TaskAssignment0\x01B:Z8github.com/indoor-mall-nav/navign/admin/tower/proto/taskb\x06proto3"

var (
	file_proto_task_proto_rawDescOnce sync.Once
	file_proto_task_proto_rawDescData []byte
)

func file_proto_task_proto_rawDescGZIP() []byte {
	file_proto_task_proto_rawDescOnce.Do(func() {
		file_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)))
	})
	return file_proto_task_proto_rawDescData
}

var file_proto_task_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_task_proto_goTypes = []any{
	(TaskType)(0),                     // 0: task.TaskType
	(Priority)(0),                     // 1: task.Priority
	(RobotState)(0),                   // 2: task.RobotState
	(*Location)(nil),                  // 3: task.Location
	(*Task)(nil),                      // 4: task.Task
	(*TaskRequest)(nil),               // 5: task.TaskRequest
	(*TaskResponse)(nil),              // 6: task.TaskResponse
	(*RobotInfo)(nil),                 // 7: task.RobotInfo
	(*RobotDistributionRequest)(nil),  // 8: task.RobotDistributionRequest
	(*RobotDistributionResponse)(nil), // 9: task.RobotDistributionResponse
	(*RobotReportRequest)(nil),        // 10: task.RobotReportRequest
	(*RobotReportResponse)(nil),       // 11: task.RobotReportResponse
	(*TaskAssignment)(nil),            // 12: task.TaskAssignment
	(*TaskAssignmentResponse)(nil),    // 13: task.TaskAssignmentResponse
	nil,                               // 14: task.Task.MetadataEntry
}
var file_proto_task_proto_depIdxs = []int32{
	0,  // 0: task.Task.type:type_name -> task.TaskType
	3,  // 1: task.Task.sources:type_name -> task.Location
	3,  // 2: task.Task.terminals:type_name -> task.Location
	1,  // 3: task.Task.priority:type_name -> task.Priority
	14, // 4: task.Task.metadata:type_name -> task.Task.MetadataEntry
	4,  // 5: task.TaskRequest.task:type_name -> task.Task
	2,  // 6: task.RobotInfo.state:type_name -> task.RobotState
	3,  // 7: task.RobotInfo.current_location:type_name -> task.Location
	7,  // 8: task.RobotDistributionResponse.robots:type_name -> task.RobotInfo
	7,  // 9: task.RobotReportRequest.robot:type_name -> task.RobotInfo
	4,  // 10: task.TaskAssignment.task:type_name -> task.Task
	10, // 11: task.OrchestratorService.ReportRobotStatus:input_type -> task.RobotReportRequest
	8,  // 12: task.OrchestratorService.GetTaskAssignment:input_type -> task.RobotDistributionRequest
	11, // 13: task.OrchestratorService.ReportRobotStatus:output_type -> task.RobotReportResponse
	12, // 14: task.OrchestratorService.GetTaskAssignment:output_type -> task.TaskAssignment
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_task_proto_init() }
func file_proto_task_proto_init() {
	if File_proto_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_task_proto_goTypes,
		DependencyIndexes: file_proto_task_proto_depIdxs,
		EnumInfos:         file_proto_task_proto_enumTypes,
		MessageInfos:      file_proto_task_proto_msgTypes,
	}.Build()
	File_proto_task_proto = out.File
	file_proto_task_proto_goTypes = nil
	file_proto_task_proto_depIdxs = nil
}
