// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/task.proto

package task

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorService_ReportRobotStatus_FullMethodName = "/task.OrchestratorService/ReportRobotStatus"
	OrchestratorService_GetTaskAssignment_FullMethodName = "/task.OrchestratorService/GetTaskAssignment"
)

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrchestratorService is implemented by Rust orchestrator (server)
// Go tower acts as client to report robot status and receive task assignments
type OrchestratorServiceClient interface {
	// ReportRobotStatus is called by Go tower to report robot status
	ReportRobotStatus(ctx context.Context, in *RobotReportRequest, opts ...grpc.CallOption) (*RobotReportResponse, error)
	// GetTaskAssignment is called by Go tower to get tasks for robots
	// This could be streaming or polling based on implementation
	GetTaskAssignment(ctx context.Context, in *RobotDistributionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskAssignment], error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) ReportRobotStatus(ctx context.Context, in *RobotReportRequest, opts ...grpc.CallOption) (*RobotReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RobotReportResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ReportRobotStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetTaskAssignment(ctx context.Context, in *RobotDistributionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskAssignment], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestratorService_ServiceDesc.Streams[0], OrchestratorService_GetTaskAssignment_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RobotDistributionRequest, TaskAssignment]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorService_GetTaskAssignmentClient = grpc.ServerStreamingClient[TaskAssignment]

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility.
//
// OrchestratorService is implemented by Rust orchestrator (server)
// Go tower acts as client to report robot status and receive task assignments
type OrchestratorServiceServer interface {
	// ReportRobotStatus is called by Go tower to report robot status
	ReportRobotStatus(context.Context, *RobotReportRequest) (*RobotReportResponse, error)
	// GetTaskAssignment is called by Go tower to get tasks for robots
	// This could be streaming or polling based on implementation
	GetTaskAssignment(*RobotDistributionRequest, grpc.ServerStreamingServer[TaskAssignment]) error
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServiceServer struct{}

func (UnimplementedOrchestratorServiceServer) ReportRobotStatus(context.Context, *RobotReportRequest) (*RobotReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportRobotStatus not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetTaskAssignment(*RobotDistributionRequest, grpc.ServerStreamingServer[TaskAssignment]) error {
	return status.Errorf(codes.Unimplemented, "method GetTaskAssignment not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}
func (UnimplementedOrchestratorServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_ReportRobotStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ReportRobotStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ReportRobotStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ReportRobotStatus(ctx, req.(*RobotReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetTaskAssignment_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RobotDistributionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServiceServer).GetTaskAssignment(m, &grpc.GenericServerStream[RobotDistributionRequest, TaskAssignment]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorService_GetTaskAssignmentServer = grpc.ServerStreamingServer[TaskAssignment]

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportRobotStatus",
			Handler:    _OrchestratorService_ReportRobotStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTaskAssignment",
			Handler:       _OrchestratorService_GetTaskAssignment_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/task.proto",
}
